 
all:
	# $(MAKE) -C cwmp_plugin_client all
	$(MAKE) -C cwmp_plugin all
	$(MAKE) -C adapter all



clean:
	$(MAKE) -C cwmp_plugin clean
	$(MAKE) -C adapter clean
	# $(MAKE) -C cwmp_plugin_client clean


install:	
	# $(MAKE) -C cwmp_plugin_client install
	$(MAKE) -C cwmp_plugin install
	$(MAKE) -C adapter install


release:
	$(MAKE) -C cwmp_plugin release
	$(MAKE) -C adapter release


