 
all:
	$(MAKE) -C cwmp_plugin all
	# $(MAKE) -C adapter all
	# $(MAKE) -C cwmp_plugin_client all

clean:
	$(MAKE) -C cwmp_plugin clean
	# $(MAKE) -C adapter clean
	# $(MAKE) -C cwmp_plugin_client clean

install:	
	$(MAKE) -C cwmp_plugin install
	# $(MAKE) -C adapter install
	# $(MAKE) -C cwmp_plugin_client install


release:
	$(MAKE) -C cwmp_plugin release
	# $(MAKE) -C adapter release


