 
all:
	# $(MAKE) -C cwmp_plugin_client all
	$(MAKE) -C cwmp_plugin all
	$(MAKE) -C adapter all

clean:
	$(MAKE) -C cwmp_plugin clean
	$(MAKE) -C adapter clean
	# $(MAKE) -C cwmp_plugin_client clean

.PHONY: all clean
