variables:
  PC_ANALYSIS_TREE: "off"
  PC_XC_WRT_DEFAULT: "on"
  PC_UNIT_TESTS: "on"
  PC_EXTRA_UNIT_TEST_DEPS: "libamxut mod-amxb-dummy"

include:
  - remote: 'https://gitlab.com/prpl-foundation/tooling/yml-templates/raw/main/.component-pipeline.yml'
