variables:
  BUILD_DEPS: libamxc libamxj libamxd libamxp libamxb libamxo libamxm libamxa sah-lib-sahtrace-dev liburiparser-dev libtr69-engine libwebsockets libevent-dev libc-ares-dev libnetmodel
  TEST_DEPS: mod-amxb-ubus
  BUILD_TARGET: tr069-manager

include:
  - remote: 'https://gitlab.com/soft.at.home/ci/gitlab-ci/raw/main/ambiorix-default-pipeline.yml'
